// react-composition-api-vite-ts/src/views/antd/components/AddForm.tsx
import { useForm } from "@/hooks/useForm";
import { DataItem } from "@/types/model";
import { Button, Form, Input, Space } from "antd";
import { defineComponent, designPage } from "plain-design-composition";

export default designPage((props: {
  onFormSubmit: (data: DataItem) => void
}) => {


  const { onSubmit, form, rules, formState, reset, labelCol, wrapperCol } = useForm();


  return () => (
    <Form
      form={form.value}

      labelCol={labelCol}
      initialValues={formState}
      onFinish={(values) => {
        onSubmit().then((values: DataItem) => {

          props.onFormSubmit(values)
        }).then(() => {
          reset()
        });
      }}
      wrapperCol={wrapperCol}
    >
      <Form.Item label="todo 名称" name="title" rules={[{ required: true, message: '请输入名称' }]}>


        <Input
          placeholder="这是必填项"
        />
      </Form.Item>
      <Form.Item wrapperCol={{ offset: 4 }}>
        <Space>
          <Button type="primary" htmlType="submit" onClick={() => {

          }}>
            提交
          </Button>
          <Button onClick={reset}>重置</Button>
        </Space>
      </Form.Item>
    </Form>
  );
});

// vue-vite-ts-setup/src/views/naive/components/AddForm.vue
<template>
  <n-form
    ref="formRef"
    label-placement="left"
    :model="formState"
    :rules="rules"
  >
    <n-form-item label="todo 名称" path="title">
      <n-input
        placeholder="这是必填项"
        v-model:value="formState.title"
      ></n-input>
    </n-form-item>
    <n-form-item>
      <n-space>
        <n-button type="primary" @click="onSubmit">提交</n-button>
        <n-button @click="reset">重置</n-button>
      </n-space>
    </n-form-item>
  </n-form>
</template>

<script lang="ts">
  import { useForm } from "@/hooks/useForm";
  import { defineComponent } from "vue";

  export default defineComponent({
    setup(props, { emit }) {
      const { onSubmit, formRef, rules, formState, reset } = useForm();

      return {
        formState,
        formRef,
        rules,
        reset,

        onSubmit: () => {
          onSubmit()
            .then(() => {
              emit("formSubmit", formState);
            })
            .then(() => {
              console.log("reset");
              reset();
            });
        },
      };
    },
  });
</script>

<style scoped>
</style>
