// react-vite-ts/src/views/antd/components/TodoTable.tsx
import { useEdit } from "@/hooks/useEdit";
import { useStore } from "@/store";
import { DataItem } from "@/types/model";
import { Button, Checkbox, Input, Popconfirm, Space, Table } from "antd";
import { ColumnProps, ColumnsType } from "antd/lib/table";
import { observer } from "mobx-react-lite";
import { useCallback, useEffect, useLayoutEffect, useState } from "react";


interface IProps {
  data: DataItem[]
  onDeleteItem: (item: DataItem) => void
}

const TodoTable = (props: IProps) => {

  const { edit, finishEdit, cancelEdit, toggle } = useEdit(props.data);

  const [currentEdit, setCurrentEdit] = useState('')

  const { todoStore } = useStore()

  let columns: ColumnsType<DataItem> = [
    {
      title: "完成",
      fixed: "left",
      width: 70,
      render: (text, record, index) => {

        return <Checkbox checked={record.finish} onChange={(e) => {
          todoStore.toggleFinish(record.id, e.target.checked)
        }}></Checkbox>
      }
    },
    {
      title: "id",
      dataIndex: "id",
    },
    {
      title: "todo名称",
      key: "title",


      render: (text, record, index): React.ReactNode => {

        const [title, setTitle] = useState(record.title)

        return (record.editing ? <Input
          value={record.title}
          onChange={(e) => {

            record.title = e.target.value
            setTitle(e.target.value)//这里必须设置一下title即使没用到也得设置，否则输入框不会变化，暂时不明原因，按理说可以去掉
          }}

        /> : <div onDoubleClick={() => {
          setCurrentEdit(record.id)
          edit(record)
        }}>
          {`${record.title}`}
        </div>)
      }
    }, {
      title: '操作',
      key: 'action',
      width: 200,
      fixed: 'right',
      render: (text, record, index): React.ReactNode => {


        const item = record

        return (


          <Space>
            {
              record.editing && (
                <>
                  <Button onClick={() => {
                    setCurrentEdit('')
                    finishEdit(item)
                  }} type="primary">保存</Button>
                  <Button onClick={() => {
                    setCurrentEdit('')
                    cancelEdit(item)
                  }}>取消</Button>
                </>
              ) || (
                <>
                  <Popconfirm
                    cancelText="取消"
                    okText="确认"
                    title="确认删除吗？"
                    onConfirm={
                      () => {


                        props.onDeleteItem(item)

                      }
                    }
                  >
                    <Button danger ghost>删除</Button>
                  </Popconfirm>
                  <Button onClick={() => {
                    setCurrentEdit(item.id)
                    edit(item)
                  }} type="primary" ghost>编辑</Button>
                </>
              )
            }

          </Space>
        )
      }
    }
  ];

  return (
    <Table
      columns={columns}
      rowKey="id"
      bordered
      pagination={false}

      dataSource={props.data}
    ></Table>
  )

}


export default observer(TodoTable)

// vue-vite-ts-setup/src/views/naive/components/TodoTable.vue
<template>
  <n-data-table
    :single-line="false"
    :row-key="rowKey"
    :columns="columns"
    :data="data"
  />
</template>

<script lang="tsx">
import { computed, defineComponent, h, PropType, VNodeChild } from "vue";
import {
  NSpace,
  NPopconfirm,
  NInput,
  NButton,
  NCheckbox
} from "naive-ui";
import { DataItem } from "@/types/model";
import { RowData } from "naive-ui/lib/data-table/src/interface";
import { useEdit } from "@/hooks/useEdit";
export default defineComponent({
  props: {
    data: {
      type: Array as PropType<DataItem[]>,
    },
    onDeleteItem: {
      type: Function as PropType<(item: DataItem) => void>
    }
  },
  setup(props) {

    const { edit, finishEdit, cancelEdit, toggle } = useEdit(props.data as DataItem[]);

    const renderActions = (item: DataItem): VNodeChild => (

      <NSpace>
        {
          item.editing && (
            <>
              <NButton onClick={() => finishEdit(item)} type="primary">保存</NButton>
              <NButton onClick={() => cancelEdit(item)}>取消</NButton>
            </>
          ) || (
            <>
              <NPopconfirm
                negative-text="取消"
                positive-text="确认"
                onPositiveClick={
                  () => {
                    props.onDeleteItem ? props.onDeleteItem(item) : undefined
                  }
                }
                v-slots={{
                  trigger: () => <NButton type='error' ghost>删除</NButton>
                }}
              >
                确认删除吗?
              </NPopconfirm>
              <NButton onClick={() => edit(item)} type="warning" ghost>编辑</NButton>
            </>
          )
        }

      </NSpace>
    )


    let columns = [
      {
        title: "完成",
        fixed: "left",
        width:70,
        render: (item: RowData) => {
          return <NCheckbox v-model={[(item as any as DataItem).finish, "checked"]}></NCheckbox>
        }
      },
      {
        title: "id",
        key: "id",
      },
      {
        title: "todo名称",
        key: "title",
        render: (item: RowData): VNodeChild => {
          return item.editing ? <NInput v-model={[item.title, "value"]}
          /> : <div onDblclick={() => edit(item as any as DataItem)}>
            {`${item.title}`}
          </div>
        }
      }, {
        title: '操作',
        key: 'action',
        width: 200,

        fixed: 'right',
        render: (rowData: RowData, rowIndex: number): VNodeChild => {
          return renderActions(rowData as any as DataItem)
        }
      }
    ];

    return {
      rowKey: (rowData: RowData): string => { return rowData.id as string },
      columns
    };
  },
});
</script>

<style scoped>
</style>
