// react-vite-ts/src/views/antd/components/AddForm.tsx
import { useForm } from "@/hooks/useForm";
import { DataItem } from "@/types/model";
import { Button, Form, Input, Space } from "antd";

const AddForm = ({ onFormSubmit }: { onFormSubmit: (data: DataItem) => void }) => {
  const { onSubmit, form, rules, formState, reset, labelCol, wrapperCol } = useForm();


  return (
    <Form

      form={form}
      initialValues={formState}

      labelCol={labelCol}

      onFinish={(values) => {
        onSubmit().then((values: DataItem) => {

          onFormSubmit(values)
        }).then(() => {
          reset()
        });
      }}
      wrapperCol={wrapperCol}
    >
      <Form.Item label="todo 名称" name="title" rules={[{ required: true, message: '请输入名称' }]}>


        <Input
          placeholder="这是必填项"

        />
      </Form.Item>
      <Form.Item wrapperCol={{ offset: 4 }}>
        <Space>
          <Button type="primary" htmlType="submit">
            提交
          </Button>
          <Button onClick={reset}>重置</Button>
        </Space>
      </Form.Item>
    </Form>
  );

}



export default AddForm

// vue-vite-ts-setup/src/views/elem/components/AddForm.vue
<template>
  <el-form
    ref="formRef"
    :model="formState"
    :rules="rules"
    label-width="80px"
    
  >
    <el-form-item label="todo名称" prop="title">
      <el-input placeholder="这是必填项" v-model="formState.title"></el-input>
    </el-form-item>

    <el-form-item>
      <el-button type="primary" @click="onSubmit">提交</el-button>
      <el-button @click="reset">重置</el-button>
    </el-form-item>
  </el-form>
</template>

<script lang="ts">
  import { defineComponent, toRaw } from "vue";
  import { useForm } from "@/hooks/useForm";
  import { DataItem } from "@/types/model";

  export default defineComponent({
    emits: {
      formSubmit: formState => {
        return { ...toRaw(formState) };
      },
    },

    setup(props, { emit }) {
      const { onSubmit, formRef, rules, formState, reset } = useForm();

      return {
        formState,
        formRef,
        rules,
        onSubmit: () => {
          onSubmit()
            .then(() => {
              emit("formSubmit", formState);
            })
            .then(() => {
              console.log("reset");
              reset();
            });
        },
        reset,
      };
    },
  });
</script>

<style scoped>
</style>
