// react-vite-ts/src/views/antd/components/AddForm.tsx
import { useForm } from "@/hooks/useForm";
import { DataItem } from "@/types/model";
import { Button, Form, Input, Space } from "antd";

const AddForm = ({ onFormSubmit }: { onFormSubmit: (data: DataItem) => void }) => {
  const { onSubmit, form, rules, formState, reset, labelCol, wrapperCol } = useForm();


  return (
    <Form

      form={form}
      initialValues={formState}

      labelCol={labelCol}

      onFinish={(values) => {
        onSubmit().then((values: DataItem) => {

          onFormSubmit(values)
        }).then(() => {
          reset()
        });
      }}
      wrapperCol={wrapperCol}
    >
      <Form.Item label="todo 名称" name="title" rules={[{ required: true, message: '请输入名称' }]}>


        <Input
          placeholder="这是必填项"

        />
      </Form.Item>
      <Form.Item wrapperCol={{ offset: 4 }}>
        <Space>
          <Button type="primary" htmlType="submit">
            提交
          </Button>
          <Button onClick={reset}>重置</Button>
        </Space>
      </Form.Item>
    </Form>
  );

}



export default AddForm

// vue-vite-ts-setup/src/views/antd/components/AddForm.vue
<template>
  <a-form
    ref="formRef"
    :model="formState"
    :label-col="labelCol"
    :rules="rules"
    @finish="onSubmit"
    :wrapper-col="wrapperCol"
  >
    <a-form-item label="todo 名称" name="title">
      <a-input placeholder="这是必填项" v-model:value="formState.title" />
    </a-form-item>

    <a-form-item :wrapperCol="{ offset: 4 }">
      <a-space>
        <a-button type="primary" html-type="submit">提交</a-button>
        <a-button @click="reset">重置</a-button>
      </a-space>
    </a-form-item>
  </a-form>
</template>
<script lang="ts">
  import { defineComponent, toRaw } from "vue";
  // import { Form, Input, Button, Space } from "ant-design-vue";
  import { useForm } from "@/hooks/useForm";
  import { useComp } from "@/hooks/useAntd";
  import { DataItem } from "@/types/model";

  export default defineComponent({
    name: "AddForm",
    emits: {
      formSubmit: formState => {
        return toRaw(formState);
      },
    },
    setup(props, { emit }) {
      const { onSubmit, formRef, rules, formState, reset,labelCol,wrapperCol } = useForm();

      return {
        formState,
        formRef,
        rules,
        reset,
        labelCol,
        wrapperCol,
        onSubmit: () => {
          onSubmit().then(()=>{
            emit("formSubmit", formState);
          }).then(()=>{
            console.log('reset')
            reset()
          })
          
        },
      };
    },
  });
</script>
