// react-vite-ts/src/views/antd/components/InfoDrawer.tsx
import { DataItem } from "@/types/model"
import { Drawer, Typography } from "antd"
import { forwardRef, Ref, useImperativeHandle, useState } from "react"

interface IProps {
  // title: string
}



function InfoDrawer(props: IProps, ref: any) {

  const [visible, setVisible] = useState(false)
  const [currentData, setCurrentData] = useState<Partial<DataItem>>({

  })

  useImperativeHandle(ref, () => ({
    show: (data: DataItem): void => {
      setVisible(true)
      if (data) {
        console.log('获取数据', data)
        setCurrentData(data)
      } else {
        setCurrentData({

        })
      }
    },

  }))


  return (

    <Drawer title="查看" placement="right" closable={false}
      onClose={() => {
        setVisible(false)
      }}
      visible={visible}>
      <Typography>
        <Typography.Title>标题：{currentData.title}</Typography.Title>
      </Typography>
    </Drawer>

  )


}


export default forwardRef(InfoDrawer)

// vue-vite-ts-setup/src/views/antd/components/InfoDrawer.vue
<script setup lang="ts">
import { DataItem } from "@/types/model";
import { reactive, ref } from "vue";

const visible = ref(false);

const currentData = reactive<DataItem>({
  id: "",
  finish: false,
  title: "",
});
defineExpose({
  show: (data?: DataItem) => {
    console.log("show", data);
    visible.value = true;
    Object.assign(currentData, data);
  },
});
</script>

<template>
  <a-drawer
    title="查看"
    placement="right"
    :closable="false"
    v-model:visible="visible"
  >
    <a-typography>
      <a-typography-title>标题：{{ currentData.title }}</a-typography-title>
    </a-typography>
  </a-drawer>
</template>
